### ISSUE TITLE
build_base_os pipeline broken for ubuntu

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_testing_jenkins#125] opened 2021-02-14 13:25 UTC
Building a  foundational base os container for both ubuntu:16.04 (ubuntu_16) and ubuntu:18.04 (ubuntu_18),
I was receiving errors in the installation of **PyOpenSSL** (same happened on **cryptography**) They related to not finding **setuptools_rust**.  centos_7, meanwhile, did not seem affected. 

Guessing that **setuptools_rust** is now an undeclared package dependency for both **PyOpenSSL** and **cryptography** , at least when installing under Python 2.7.  Things have been tracking rather badly on Python 2.7 since support was dropped, so probably the better (long term more comfortable) type of solution for this and similar issues is: Do  everything we can with Python3 .

**Comment by trel** [comment] 2021-02-14 15:17
This is an intentional duplicate of #123 - but it's already closed/complete?

Is there more work to be done to get build_base_os working again?

**Comment by d-w-moore** [comment] 2021-02-14 15:19
No , this does it. I was able to build irods again, on both ubuntu's and that was the aim

**Comment by trel** [comment] 2021-02-14 15:26
Gotcha - thanks.

**Closed** 2021-02-14 15:27 UTC
Labels: duplicate
